"""
Django settings for ednp project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Reads the .env file in the project root (gitignored — see .env.example for
# the template) into the environment, so secrets never live in this file.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'SECRET_KEY is not set. Copy .env.example to .env and fill in a real '
        'secret key (python -c "from django.core.management.utils import '
        'get_random_secret_key; print(get_random_secret_key())").'
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (secure/closed) if not set — DEBUG must be turned on
# explicitly for local dev, in .env, not baked in here.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Comma-separated in .env, e.g. ALLOWED_HOSTS=localhost,127.0.0.1,ednp.example.com
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'registrar',
    'clergy',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.SingleSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ednp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'registrar.context_processors.document_stats',
                'clergy.context_processors.document_stats',
            ],
        },
    },
]

WSGI_APPLICATION = 'ednp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

def _env(*names, default=''):
    # First non-empty value wins: DB_* (local .env) or Railway's MYSQL* variables.
    for name in names:
        value = os.environ.get(name)
        if value:
            return value
    return default


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': _env('DB_NAME', 'MYSQLDATABASE', 'MYSQL_DATABASE', default='ednp_clergy_records'),
        'USER': _env('DB_USER', 'MYSQLUSER', default='root'),
        'PASSWORD': _env('DB_PASSWORD', 'MYSQLPASSWORD'),
        'HOST': _env('DB_HOST', 'MYSQLHOST', default='localhost'),
        'PORT': _env('DB_PORT', 'MYSQLPORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# collectstatic target; served by WhiteNoise when DEBUG=False (e.g. in the container).
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
# Overridable so a container can point this at a mounted volume (uploads must
# outlive redeploys).
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))

LOGIN_URL = 'index'

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB


# Cookie security — tied to DEBUG rather than a separate toggle, so it can't
# be left misconfigured: DEBUG=True (local dev over plain http) keeps cookies
# usable without HTTPS; DEBUG=False (production) marks them Secure, which
# requires the site to actually be served over HTTPS or logins will silently
# stop working — that's intentional, it should fail loud, not leak quietly.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True


# Behind a TLS-terminating proxy (Railway, etc.): trust its forwarded-proto
# header so Django sees requests as HTTPS, and allow its origin for CSRF.
# Comma-separated, e.g. CSRF_TRUSTED_ORIGINS=https://your-app.up.railway.app
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]
if os.environ.get('BEHIND_PROXY', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
