# Generated by Django 4.2.30 on 2026-09-21 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClergyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('civil_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=10)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('baptism_place', models.CharField(blank=True, max_length=150)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('confirmation_place', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('ordination_date', models.DateField(blank=True, null=True)),
                ('ordination_place', models.CharField(blank=True, max_length=150)),
                ('assignment', models.CharField(blank=True, max_length=150)),
                ('previous_assignment', models.CharField(blank=True, max_length=150)),
                ('education', models.TextField(blank=True)),
                ('other_information', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('diocese', models.CharField(blank=True, default='Episcopal Diocese of Northern Philippines', max_length=150)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('verification', models.CharField(choices=[('Verified', 'Verified'), ('For Verification', 'For Verification')], default='For Verification', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='registrar.clergyrecord')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clergy_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clergy_profiles',
            },
        ),
    ]
