# Generated by Django 4.2.30 on 2026-09-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clergyprofile',
            name='pagibig_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Pag-IBIG Number'),
        ),
        migrations.AddField(
            model_name='clergyprofile',
            name='philhealth_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='PhilHealth Number'),
        ),
        migrations.AddField(
            model_name='clergyprofile',
            name='sss_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='SSS Number'),
        ),
    ]
