# Generated by Django 4.2.30 on 2026-09-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clergy', '0002_clergyprofile_pagibig_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clergyprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='baptism_date',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='confirmation_date',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='contract_end',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='ordination_date',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='suffix',
        ),
    ]
