# Generated by Django 4.2.30 on 2026-10-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy', '0003_remove_clergyprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clergyprofile',
            name='ordination_place',
        ),
        migrations.RemoveField(
            model_name='clergyprofile',
            name='previous_assignment',
        ),
        migrations.AddField(
            model_name='clergyprofile',
            name='children_names',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clergyprofile',
            name='marriage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clergyprofile',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='clergyprofile',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
