# Generated by Django 4.2.30 on 2026-09-21 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClergyRecord',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('ordination_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('assignment', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Assigned Abroad', 'Assigned Abroad'), ('Inactive', 'Inactive'), ('Retired', 'Retired')], default='Active', max_length=20)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clergy_records',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Deaneries',
                'db_table': 'deaneries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish_name', models.CharField(max_length=150)),
                ('place_name', models.CharField(blank=True, max_length=150, null=True)),
                ('deanery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='registrar.deanery')),
            ],
            options={
                'db_table': 'parishes',
                'ordering': ['deanery_id', 'id'],
            },
        ),
    ]
