# Generated by Django 4.2.30 on 2026-09-22 13:27

from django.db import migrations, models
import django.db.models.deletion
import registrar.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('required_from_rank', models.CharField(choices=[('postulancy', 'Postulancy'), ('deacon', 'Deacon'), ('priest', 'Priest'), ('bishop', 'Bishop'), ('none', 'Not rank-gated')], default='none', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('validity_period_months', models.PositiveIntegerField(blank=True, help_text='Leave blank if this document type does not expire.', null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'document_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clergyrecord',
            name='rank',
            field=models.CharField(choices=[('postulancy', 'Postulancy'), ('deacon', 'Deacon'), ('priest', 'Priest'), ('bishop', 'Bishop')], default='postulancy', max_length=20),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=registrar.models.clergy_document_upload_path)),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='registrar.documenttype')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registrar.clergyrecord')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['document_type__name'],
                'unique_together': {('record', 'document_type')},
            },
        ),
    ]
