# Generated by Django 4.2.30 on 2026-09-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_documenttype_clergyrecord_rank_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='submitted_date',
            field=models.DateField(),
        ),
    ]
