# Generated by Django 4.2.30 on 2026-09-22 16:20

from django.db import migrations, models


def remap_old_statuses(apps, schema_editor):
    ClergyRecord = apps.get_model('registrar', 'ClergyRecord')
    ClergyRecord.objects.filter(status='Assigned Abroad').update(status='Missionary to Other Diocese')
    ClergyRecord.objects.filter(status='Inactive').update(status='On Leave')


def restore_old_statuses(apps, schema_editor):
    ClergyRecord = apps.get_model('registrar', 'ClergyRecord')
    ClergyRecord.objects.filter(status='Missionary to Other Diocese').update(status='Assigned Abroad')
    ClergyRecord.objects.filter(status='On Leave').update(status='Inactive')


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_alter_document_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clergyrecord',
            name='leave_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clergyrecord',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Missionary to Other Diocese', 'Missionary to Other Diocese'), ('Retired', 'Retired')], default='Active', max_length=40),
        ),
        migrations.RunPython(remap_old_statuses, restore_old_statuses),
    ]
