# Generated by Django 4.2.30 on 2026-10-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0006_backuparchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='clergyrecord',
            name='bishop_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bishop'),
        ),
        migrations.AddField(
            model_name='clergyrecord',
            name='consecration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Bishop Consecration'),
        ),
        migrations.AddField(
            model_name='clergyrecord',
            name='deanery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clergy_records', to='registrar.deanery'),
        ),
        migrations.AddField(
            model_name='clergyrecord',
            name='diaconate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Ordination to Diaconate'),
        ),
        migrations.AddField(
            model_name='clergyrecord',
            name='holy_orders_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date for Holy Orders / Synod Entry'),
        ),
        migrations.AddField(
            model_name='clergyrecord',
            name='ordination_place',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clergyrecord',
            name='previous_assignment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clergyrecord',
            name='service_history',
            field=models.TextField(blank=True, null=True, verbose_name='Deployment & Service History'),
        ),
        migrations.AlterField(
            model_name='clergyrecord',
            name='ordination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Ordination to Priesthood'),
        ),
    ]
