# Generated by Django 4.2.30 on 2026-10-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0007_clergyrecord_bishop_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='uploaded_by',
            field=models.CharField(choices=[('clergy', 'Clergy Submission'), ('registrar', 'Registrar Upload')], default='clergy', help_text='Who normally provides this document — only affects which checklist it appears under and who gets an upload control for it; the Registrar can still manage either group.', max_length=20),
        ),
    ]
