# Generated by Django 4.2.30 on 2026-10-01 04:48

from django.db import migrations

REGISTRAR_UPLOADED_NAMES = [
    'Grades',
    'Ember Letter',
    'Seminary Evaluation',
    'Deployment Notice - Bishop',
    'Letter of Institution',
    'Ordination Entry / Holy Orders Document',
]


def set_registrar_uploaded(apps, schema_editor):
    DocumentType = apps.get_model('registrar', 'DocumentType')
    DocumentType.objects.filter(name__in=REGISTRAR_UPLOADED_NAMES).update(uploaded_by='registrar')


def reverse(apps, schema_editor):
    DocumentType = apps.get_model('registrar', 'DocumentType')
    DocumentType.objects.filter(name__in=REGISTRAR_UPLOADED_NAMES).update(uploaded_by='clergy')


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0008_documenttype_uploaded_by'),
    ]

    operations = [
        migrations.RunPython(set_registrar_uploaded, reverse),
    ]
