# Generated by Django 4.2.30 on 2026-10-02 14:33

from django.db import migrations, models


def seed_clergy_counter(apps, schema_editor):
    """Start the counter at the highest CLG-### already in use."""
    import re
    ClergyRecord = apps.get_model('registrar', 'ClergyRecord')
    IdCounter = apps.get_model('registrar', 'IdCounter')
    highest = 0
    for existing_id in ClergyRecord.objects.values_list('id', flat=True):
        m = re.search(r'(\d+)$', existing_id)
        if m:
            highest = max(highest, int(m.group(1)))
    IdCounter.objects.update_or_create(name='clergy_record', defaults={'last_value': highest})


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0009_set_registrar_uploaded_document_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCounter',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'id_counters',
            },
        ),
        migrations.RunPython(seed_clergy_counter, migrations.RunPython.noop),
    ]
